import org.scalatest.matchers.should.Matchers
import org.scalatest.GivenWhenThen
import org.scalatest.featurespec.AnyFeatureSpec


class DepartureEndtoendXIP6Spec extends AnyFeatureSpec with GivenWhenThen{

  Feature("End to end journey for Prelodged Northern Ireland office of departure") {

    Scenario("01 Security 'ENS' - Guarantee 'B' - Inland Mode 'Rail' - Border Means 'Air' - Container Ind 'No' - CL213 & CL754 Documents") {
      And("I enter 1234567 on the What is the TIR carnet reference? page")
      And("I choose radio option Exit summary declaration (EXS) on the Which type of safety and security details do you want to add? page")
      And("I submit the Check your answers page")
      When("I click the Add trader details link on the Declaration summary page")
      And("I choose radio option Yes on the Do you know the transit holder’s EORI number? page")
      And("I enter GB123456123456 on the What is the transit holder’s EORI number? page")
      And("I choose radio option No on the Do you want to add a contact for the transit holder? page")
      And("I enter ABC/123/12345 on the What is the TIR holder’s identification number? page")
      And("I choose radio option No on the Are you acting as a representative? page")
      And("I choose radio option Yes on the Do you know the consignor’s EORI number or TIN? page")
      And("I enter IT12312313 on the What is the consignor’s EORI number or TIN? page")
      And("I choose radio option No on the Do you want to add a contact for the consignor? page")
      And("I choose radio option Yes on the Do you know the consignee’s EORI number or TIN? page")
      And("I enter GE00101001 on the What is the consignee’s EORI number or TIN? page")
      And("I submit on the Check your answers section Trader details page")
      Then("I should be on the Declaration summary page")
      And("I should see Completed status for trader details on the Declaration summary page")
      When("I click the Add route details link on the Declaration summary page")
      And("I choose radio option No on the Do you want to add a specific circumstance indicator? page")
      And("I select Italy on the What country is the office of destination in? page")
      And("I select IT on the Where in Italy is the office of destination? page")
      And("I choose radio option No on the Are you using a binding itinerary? page")
      And("I select Andorra on the Which country do you want to add to the transit route? page")
      When("I choose radio option Yes on the You have added 1 country to the transit route page")
      And("I select Argentina on the Which country do you want to add to the transit route? page")
      When("I choose radio option No on the You have added 2 countries to the transit route page")
      And("I submit on the Check your answers section Transit route page")
      And("I choose radio option Yes on the Do you want to add a location of goods? page")
      And("I choose radio option Designated location on the Which type of location is it? page")
      And("I choose radio option Customs office identifier on the How do you want to identify the location of goods? page")
      And("I select XI on the departure location of goods customs office identification page")
      And("I submit on the Check your answers section Location of goods page")
      And("I choose radio option No on the Do you want to add a place of loading? page")
      And("I choose radio option No on the Do you want to add a place of unloading? page")
      And("I submit on the Check your answers section Places of loading and unloading page")
      And("I submit on the Check your answers section Route details page")
      Then("I should be on the Declaration summary page")
      And("I click the Add guarantee details link on the Declaration summary page")
      Then("I click the Continue button on the Guarantee added for TIR declaration page")
      And("I should be on the Declaration summary page")
      When("I click the Add transport details link on the Declaration summary page")
      And("I choose radio option Yes on the Do you want to use the same UCR for all items? page")
      And("I enter UCR23456 on the What is the UCR? page")
      And("I choose radio option Yes on the Are all the items being dispatched from the same country? page")
      And("I select United Kingdom on the What is the country of dispatch? page")
      And("I choose radio option Yes on the Are the goods being transported to another country after the end of this transit movement? page")
      And("I choose radio option No on the Are all the items being transported to the same country? page")
      And("I choose radio option Not sure on the Are you using any shipping containers to transport the goods? page")
      And("I choose radio option Yes on the Do you want to add an inland mode of transport? page")
      And("I choose radio option Rail on the Which inland mode of transport are you using? page")
      And("I choose radio option Train number on the inland mode Which identification do you want to use for this vehicle? page")
      And("I enter registration number 1234567 on the What is the identification number for this? page")
      And("I select United Kingdom on the inland mode What country is this vehicle registered to? page")
      And("I submit on the Check your answers section Departure means of transport page")
      And("I select radio option No on the You have added 1 departure means of transport page")
      And("I choose radio option Air on the How is the transit crossing the border? page")
      And("I choose radio option registration number of the aircraft on the border mode Which identification do you want to use for this vehicle? page")
      And("I enter identification GB1234567 on the What is the identification number for this? page")
      And("I select United Kingdom on the border mode What country is this vehicle registered to? page")
      And("I select Abruzzo on the Where is the customs office at the border? page")
      And("I enter conveyance number GB123456123456 on the What is the conveyance reference number? page")
      And("I submit on the Check your answers section Modes and means of transport page")
      When("I choose radio option No on the Do you want to add a supply chain actor for all items? page")
      When("I choose radio option No on the Do you want to add a carrier? page")
      And("I choose radio option No on the Do you want to add a method of payment for transport charges? page")
      And("I click radio option No on the Do you want to add an additional reference for all items? page")
      And("I click radio option No on the Do you want to add any additional information for all items? page")
      And("click the Change link for Do you want to use the same Unique Consignment Reference? on the Transport details Check your answers page")
      And("I choose radio option No on the Do you want to use the same UCR for all items? page")
      And("click the Change link for Are all the items being dispatched from the same country? on the Transport details Check your answers page")
      And("I choose radio option No on the Are all the items being dispatched from the same country? page")
      And("click the Change link for Are all the items being transported to the same country? on the Transport details Check your answers page")
      And("I choose radio option No on the Are all the items being transported to the same country? page")
      And("I submit on the Check your answers section Transport details page")
      Then("I should be on the Declaration summary page")
      When("I click the Add documents link on the Declaration summary page")
      And("I click radio option Yes on the Do you want to add any documents? page")
      And("I click radio option No on the Do you want to use this document for all items? page")
      Then("I select Supporting - (C673) Catch certificate on the What type of document do you want to add? page")
      And("I enter RefNoCL213Doc1 on the What is the document’s reference number? page")
      And("I click radio option No on the Do you want to add a line item number? page")
      And("I click radio option No on the Do you want to add any additional information for this document? page")
      And("I submit on the Check your answers section Documents page")
      And("I choose radio option Yes on the You have added 1 document page")
      And("I click radio option Yes on the Do you want to use this document for all items? page")
      And("I select Transport - (N741) Master airwaybill on the What type of document do you want to add? page")
      And("I enter air1234 on the What is the document’s reference number? page")
      And("I submit on the Check your answers section Documents page")
      And("I choose radio option Yes on the You have added 2 documents page")
      And("I click radio option No on the Do you want to use this document for all items? page")
      And("I select Previous - (C605) Information sheet INF3 on the What type of document do you want to add? page")
      And("I enter 1234 on the What is the document’s reference number? page")
      And("I click radio option No on the Do you want to add any additional information for this document? page")
      And("I submit on the Check your answers section Documents page")
      And("I choose radio option No on the You have added 3 documents page")
      When("I click the Add items link on the Declaration summary page")
      And("I enter This is a description of Item 1 on the Enter a description of item 1 page")
      And("I select United Kingdom on the What is the item’s country of dispatch? page")
      And("I select Italy on the What is the item’s country of destination? page")
      And("I choose radio option Yes on the Do you want to add a Unique Consignment Reference? page")
      And("I enter UCR12312 on the What is the Unique Consignment Reference? page")
      And("I click radio option Yes on the Do you want to add a Customs Union and Statistics code? page")
      And("I enter 0010002-7 on the What is the Customs Union and Statistics code? page")
      And("I click radio option Yes on the Do you want to add a commodity code? page")
      And("I enter 010130 on the What is the commodity code? page")
      And("I click radio option Yes on the Do you want to add a combined nomenclature code? page")
      And("I enter A1 on the What is the combined nomenclature code? page")
      And("I click radio option No on the Does the item contain any dangerous goods? page")
      And("I enter 100 on the What is the item’s gross weight? page")
      And("I click radio option No on the Do you want to add the item’s net weight? page")
      And("I click radio option No on the Do you want to add supplementary units? page")
      And("I select (VL) Bulk, liquid on the What type of package are you using for the item? page")
      And("I click radio option No on the Do you want to add a shipping mark? page")
      And("I click radio option No on the You have added 1 type of package page")
      And("I click radio option No on the Do you want to add a supply chain actor for this item? page")
      And("I click radio option Yes on the You have attached 1 document to this item page")
      And("I select Supporting - (C673) Catch certificate - RefNoCL213Doc1 on the Which document do you want to attach? page")
      And("I click radio option No on the You have attached 2 documents to this item page")
      And("I click radio option No on the Do you want to add an additional reference for this item? page")
      And("I click radio option No on the Do you want to add any additional information for this item? page")
      And("I submit on the Check your answers section Items page")
      And("I click radio option No on the You have added 1 item page")
      And("I click the Confirm and send button on the Declaration summary page")
      And("I click the Sign out link on the Departure declaration sent page")
    }
  }
}
